// Resume content + i18n. Content is structured (objects, not strings) so it
// stays semantic for AI parsing and easy to translate.

const RESUME = {
  name: "Eiram Emmanuel Araujo Chávez",
  short: "Eiram Araujo",
  email: "eiram.araujo@eiramaraujodev.com",
  location: "Mexico",
  links: {
    linkedin: "https://www.linkedin.com/in/eiram-araujo-14256b207/",
    github: "https://github.com/EiramAraujo",
    website: "https://eiramaraujodev.com",
  },
  // Stable, machine-friendly facts. Strings here aren't translated — they're
  // identifiers/dates the AI summary needs verbatim.
  experience: [
    {
      id: "epicor-pd",
      company: "Epicor Software",
      location: "Monterrey, MX",
      role_key: "role_epicor_pd",
      start: "2023-01",
      end: null, // present
      bullets_keys: ["epicor_pd_b1", "epicor_pd_b2", "epicor_pd_b3", "epicor_pd_b4"],
      stack: ["C#", ".NET", "Angular", "ERP", "SQL"],
    },
    {
      id: "hoffmann",
      company: "Hoffmann Group",
      location: "Munich, DE",
      role_key: "role_hoffmann",
      start: "2022-04",
      end: "2022-09",
      bullets_keys: ["hoffmann_b1", "hoffmann_b2", "hoffmann_b3"],
      stack: ["Python", "Embedded", "LPUART", "Bluetooth", "Firmware"],
    },
    {
      id: "epicor-intern",
      company: "Epicor Software",
      location: "Monterrey, MX",
      role_key: "role_epicor_intern",
      start: "2021-06",
      end: "2021-09",
      bullets_keys: ["epicor_intern_b1"],
      stack: ["Angular", "TypeScript", "Front-End"],
    },
  ],
  education: [
    {
      id: "uanl",
      school: "Universidad Autónoma de Nuevo León",
      degree_key: "edu_uanl",
      start: "2017-09",
      end: "2022-12",
      location: "Monterrey, MX",
    },
    {
      id: "ovgu",
      school: "Otto-von-Guericke Universität Magdeburg",
      degree_key: "edu_ovgu",
      start: "2021-10",
      end: "2022-09",
      location: "Magdeburg, DE",
    },
  ],
  projects: [
    {
      id: "flash-tool",
      title_key: "proj_flash_t",
      desc_key: "proj_flash_d",
      stack: ["Python", "LPUART", "Embedded"],
      year: "2022",
      image: "assets/flasher-project.png",
    },
    {
      id: "social-bot",
      title_key: "proj_bot_t",
      desc_key: "proj_bot_d",
      stack: ["JavaScript", "Pyton", "REST API", "Embedded Systems"],
      year: "2022",
      image: "assets/bot-socialmedia-project.png",
    },
    {
      id: "bank-db",
      title_key: "proj_bank_t",
      desc_key: "proj_bank_d",
      stack: ["MariaDB", "Spring Boot", "Java"],
      year: "2021",
      image: "assets/database-project.png",
    },
    {
      id: "traffic-app",
      title_key: "proj_traffic_t",
      desc_key: "proj_traffic_d",
      stack: ["Ionic", "Angular", "Google Maps API"],
      year: "2021",
      image: "assets/ionic-app-project.png",
    }
  ],
  skills: {
    languages: ["C#", "Python", "JavaScript", "TypeScript"],
    frameworks: [".NET", "Angular", "Node.js", "Spring Boot", "Ionic"],
    practice: [
      "REST API design",
      "Server administration",
      "Working with AI tools",
      "Code documentation",
      "Mentoring & onboarding",
    ],
  },
  certifications: [
    { id: "scrum", title: "Certified Scrum Developer", issuer: "Scrum México", year: "2025" },
    { id: "toefl", title: "TOEFL iBT — Score 94", issuer: "ETS", year: "2022" },
    { id: "goethe", title: "Goethe-Zertifikat B2", issuer: "Goethe-Institut", year: "2020" },
    { id: "aws", title: "AWS Introduction", issuer: "AWS", year: "2021" },
  ],
  spoken: [
    { code: "es", level: "Native" },
    { code: "en", level: "Professional (TOEFL 94)" },
    { code: "de", level: "B2 (Goethe)" },
	{ code: "jp", level: "Intermediate" },
  ],
  testimonials: [
    {
      id: "t1",
      quote_key: "tm_q1",
      author: "-i.V Katrin Schnidler",
      relation_key: "tm_r1",
      company: "Hoffmann Group",
    },
    {
      id: "t2",
      quote_key: "tm_q2",
      author: "Team Lead, Firmware",
      relation_key: "tm_r2",
      company: "Hoffmann Group",
    },
    {
      id: "t3",
      quote_key: "tm_q3",
      author: "Professor, Computer Science",
      relation_key: "tm_r3",
      company: "UANL",
    },
  ],
};

const I18N = {
  en: {
    // Nav
    nav_about: "About",
    nav_work: "Work",
    nav_projects: "Projects",
    nav_voices: "Voices",
    nav_contact: "Contact",
    // Hero
    role_title: "Software Developer",
    hero_h1_a: "I build software that ",
    hero_h1_b: "ships",
    hero_h1_c: ", documents itself, and scales.",
    hero_lede:
      "Software developer with 3+ years on a large-scale ERP and embedded firmware experience across Mexico and Germany. I write clear code, mentor new hires, and use AI as a force multiplier.",
    hero_cta_work: "See work",
    hero_cta_cv: "Download CV",
    // Quick facts
    qf_years: "Years building production software",
    qf_countries: "Countries shipped from",
    qf_langs: "Spoken languages",
    qf_focus: "Current focus",
    // About
    about_h: "About",
    about_p1:
      "I'm a Software Developer graduated from UANL (with a year at Otto-von-Guericke in Magdeburg). I currently build features on a large-scale ERP at Epicor — the kind of software where careful details matters more than a flashy demo.",
    about_p2:
      "Before that, I worked on embedded firmware at Hoffmann Group in Munich, flashing high-precision BLE industrial tools over LPUART. That mix — enterprise scale and low-level pragmatism — is how I approach problems.",
    about_p3:
      "I document what I build, mentor people coming in behind me, and treat AI tools as serious leverage rather than a novelty.",
    // Work
    work_e: "Work",
	work_h: "Experience",
    work_present: "Present",
    role_epicor_pd: "Product Developer",
    role_hoffmann: "Software Developer & Test Intern",
    role_epicor_intern: "Software Developer Intern",
    epicor_pd_b1: "Build and maintain features on a global-scale ERP used by enterprise customers.",
    epicor_pd_b2: "Document complex modules so new hires can quickly ramp.",
    epicor_pd_b3: "Onboard and mentor incoming developers on the team.",
    epicor_pd_b4: "Adopt AI-assisted workflows to ship faster without sacrificing review quality.",
    hoffmann_b1: "Built a flashing program for high-precision BLE industrial tools over LPUART.",
    hoffmann_b2: "Wrote automated tests for electronic industrial tools.",
    hoffmann_b3: "Tested firmware end-to-end and reported reproducible bugs to the firmware team.",
    epicor_intern_b1: "Front-end development on the company's flagship ERP.",
    // Projects
	proj_e: "Applying knowledge",
    proj_h: "Projects",
    proj_lede: "A few things I've shipped.",
    proj_bot_t: "Social media bot + REST API",
    proj_bot_d: "JavaScript bot backed by a NodeJS. The bot activates commands that run both on system level and hardware level.",
    proj_bank_t: "Database Management",
    proj_bank_d: "MariaDB + Spring Boot application modeling a small bank's accounts, transfers, and general information.",
    proj_traffic_t: "Mobile Application Development",
    proj_traffic_d: "Development of a mobile application for crash and traffic reporting using the Ionic Framework and Google API services.",
    proj_flash_t: "Industrial tool flasher",
    proj_flash_d: "Firmware flashing utility for a precision BLE industrial tool family — LPUART, written in Python.",
    proj_view: "View details",
    proj_image_placeholder: "Project shot",
    // Voices
	voices_e: "References",
    voices_h: "Voices",
    voices_lede: "Excerpts from references — full letters available on request.",
    tm_q1: "[...]Mr. Araujo Chavez always acquired excellent technical knowledge in an impressively short period of time and was always able to apply and implement this knowledge in his daily work with very good results.",
    tm_q2: "He moved between firmware testing and tooling without missing a beat. Pragmatic, careful, easy to work with.",
    tm_q3: "A standout student — curious, methodical, and consistently in the top of his cohort across six semesters.",
    tm_r1: "Head of Development in Advanced Control Systems",
    tm_r2: "Team lead",
    tm_r3: "Thesis advisor",
    // Skills / certs
    skills_h: "Skills",
    skills_langs: "Languages",
    skills_frameworks: "Frameworks & runtimes",
    skills_practice: "Practice",
    certs_h: "Certifications",
    spoken_h: "Languages I speak",
    // Contact
    contact_h: "Let's talk",
    contact_lede: "I'm open to Software Engineering roles — backend or embedded.",
    contact_email: "Email",
    contact_resume: "PDF résumé",
    // Footer
    footer_built: "Eiram Araujo",
    footer_year: "2026",
    // Tweaks
    tw_theme: "Theme",
    tw_accent: "Accent",
    tw_motion: "Motion",
    tw_density: "Density",
    tw_font: "Display font",
    // Misc
    lang_label: "Language",
    skip_link: "Skip to content",
    edu_uanl: "B.Sc. Computer Science",
    edu_ovgu: "B.Sc. Computer Science — exchange semester",
    education_h: "Education",
    lang_es: "Spanish",
    lang_en: "English",
    lang_de: "German",
    lang_jp: "Japanese",
  },

  es: {
    nav_about: "Sobre mí",
    nav_work: "Trabajo",
    nav_projects: "Proyectos",
    nav_voices: "Voces",
    nav_contact: "Contacto",
    role_title: "Desarrollador de Software",
    hero_h1_a: "Construyo software que ",
    hero_h1_b: "se entrega",
    hero_h1_c: ", se documenta y escala.",
    hero_lede:
      "Desarrollador con más de 3 años en un ERP a gran escala y experiencia en firmware embebido entre México y Alemania. Escribo código claro, formo a nuevos compañeros y uso la IA como multiplicador de fuerza.",
    hero_cta_work: "Ver trabajo",
    hero_cta_cv: "Descargar CV",
    qf_years: "Años en producción",
    qf_countries: "Países desde donde he entregado",
    qf_langs: "Idiomas",
    qf_focus: "Foco actual",
    about_h: "Sobre mí",
    about_p1:
      "Soy un desarrollador de software graduado de la UANL (con un año en Otto-von-Guericke, Magdeburgo). Hoy construyo funcionalidades en un ERP a gran escala en Epicor — software donde los detalles cuidadosos pesan más que un demo llamativo.",
    about_p2:
      "Antes trabajé en firmware embebido en Hoffmann Group, en Múnich, programando herramientas industriales BLE de alta precisión vía LPUART. Esa mezcla — escala empresarial y pragmatismo de bajo nivel — es como abordo los problemas.",
    about_p3:
      "Documento lo que construyo, acompaño a quienes llegan después de mí y trato a las herramientas de IA como un apalancamiento serio, no como una novedad.",
    work_e: "Trabajo",
    work_h: "Experiencia",
    work_present: "Actualidad",
    role_epicor_pd: "Product Developer",
    role_hoffmann: "Software Developer & Test Intern",
    role_epicor_intern: "Software Developer Intern",
    epicor_pd_b1: "Desarrollo y mantenimiento de funcionalidades en un ERP global usado por clientes empresariales.",
    epicor_pd_b2: "Documentación de módulos complejos para que nuevos miembros se incorporen rápidamente.",
    epicor_pd_b3: "Onboarding y mentoría a desarrolladores que se integran al equipo.",
    epicor_pd_b4: "Adopción de flujos asistidos por IA para entregar más rápido sin sacrificar calidad de revisión.",
    hoffmann_b1: "Programa de flasheo para herramientas industriales BLE de alta precisión vía LPUART.",
    hoffmann_b2: "Pruebas automatizadas para herramientas industriales electrónicas.",
    hoffmann_b3: "Pruebas de firmware end-to-end y reporte de bugs reproducibles al equipo de firmware.",
    epicor_intern_b1: "Desarrollo Front-End en el ERP insignia de la compañía.",
    proj_e: "Aplicando conocimiento",
    proj_h: "Proyectos",
    proj_lede: "Algunas cosas que he construido.",
    proj_bot_t: "Bot de redes sociales + API REST",
    proj_bot_d: "Bot en JavaScript respaldado por NodeJS. El bot activa comandos que se ejecutan tanto a nivel de sistema como de hardware.",
    proj_bank_t: "Gestión de bases de datos",
    proj_bank_d: "Aplicación MariaDB + Spring Boot que modela cuentas, transferencias e información general de un banco pequeño.",
    proj_traffic_t: "Desarrollo de aplicaciones móviles",
    proj_traffic_d: "Desarrollo de una aplicación móvil para reporte de accidentes y tráfico usando el framework Ionic y servicios de la API de Google.",
    proj_flash_t: "Flasheador de herramienta industrial",
    proj_flash_d: "Utilidad de flasheo de firmware para una familia de herramientas BLE de precisión — LPUART, escrita en Python.",
    proj_view: "Ver detalles",
    proj_image_placeholder: "Imagen del proyecto",
    voices_e: "Referencias",
    voices_h: "Voces",
    voices_lede: "Extractos de referencias — cartas completas disponibles a petición.",
    tm_q1: "[...]el Sr. Araujo Chávez siempre adquirió excelentes conocimientos técnicos en un tiempo impresionantemente corto y siempre fue capaz de aplicarlos e implementarlos en su trabajo diario con muy buenos resultados.",
    tm_q2: "Se movió entre testing de firmware y tooling sin perder ritmo. Pragmático, cuidadoso y fácil de tratar.",
    tm_q3: "Estudiante destacado — curioso, metódico y consistentemente entre los mejores de su generación durante seis semestres.",
    tm_r1: "Jefe de Desarrollo en Sistemas de Control Avanzados",
    tm_r2: "Líder de equipo",
    tm_r3: "Asesor de tesis",
    skills_h: "Habilidades",
    skills_langs: "Lenguajes",
    skills_frameworks: "Frameworks & runtimes",
    skills_practice: "Práctica",
    certs_h: "Certificaciones",
    spoken_h: "Idiomas que hablo",
    contact_h: "Hablemos",
    contact_lede: "Estoy abierto a roles de Ingeniería de Software — backend o embebido.",
    contact_email: "Correo",
    contact_resume: "CV en PDF",
    footer_built: "Eiram Araujo",
    footer_year: "2026",
    tw_theme: "Tema",
    tw_accent: "Acento",
    tw_motion: "Animación",
    tw_density: "Densidad",
    tw_font: "Fuente",
    lang_label: "Idioma",
    skip_link: "Saltar al contenido",
    edu_uanl: "Lic. en Ciencias Computacionales",
    edu_ovgu: "Lic. en Ciencias Computacionales — semestre de intercambio",
    education_h: "Educación",
    lang_es: "Español",
    lang_en: "Inglés",
    lang_de: "Alemán",
    lang_jp: "Japonés",
  },

  de: {
    nav_about: "Über mich",
    nav_work: "Arbeit",
    nav_projects: "Projekte",
    nav_voices: "Stimmen",
    nav_contact: "Kontakt",
    role_title: "Softwareentwickler",
    hero_h1_a: "Ich baue Software, die ",
    hero_h1_b: "ausgeliefert wird",
    hero_h1_c: ", sich selbst dokumentiert und skaliert.",
    hero_lede:
      "Softwareentwickler mit 3+ Jahren an einem groß angelegten ERP und Erfahrung in Embedded-Firmware in Mexiko und Deutschland. Ich schreibe klaren Code, betreue neue Kolleg:innen und nutze KI als Hebel.",
    hero_cta_work: "Arbeit ansehen",
    hero_cta_cv: "Lebenslauf laden",
    qf_years: "Jahre in der Produktion",
    qf_countries: "Länder, aus denen ich geliefert habe",
    qf_langs: "Sprachen",
    qf_focus: "Aktueller Fokus",
    about_h: "Über mich",
    about_p1:
      "Ich bin ein Softwareentwickler und Absolvent der UANL (mit einem Jahr an der Otto-von-Guericke-Universität Magdeburg). Aktuell baue ich Features in einem groß angelegten ERP bei Epicor — Software, in der sorgfältige Details mehr zählen als eine schicke Demo.",
    about_p2:
      "Davor habe ich bei Hoffmann Group in München an Embedded-Firmware gearbeitet und hochpräzise BLE-Industriewerkzeuge per LPUART geflasht. Diese Mischung — Enterprise-Skala und Low-Level-Pragmatismus — prägt meine Herangehensweise.",
    about_p3:
      "Ich dokumentiere, was ich baue, betreue Nachfolger:innen und behandle KI-Tools als ernsthafte Hebelwirkung, nicht als Spielerei.",
    work_e: "Arbeit",
    work_h: "Berufserfahrung",
    work_present: "Heute",
    role_epicor_pd: "Product Developer",
    role_hoffmann: "Software Developer & Test Intern",
    role_epicor_intern: "Software Developer Intern",
    epicor_pd_b1: "Entwicklung und Wartung von Features in einem global eingesetzten ERP für Enterprise-Kunden.",
    epicor_pd_b2: "Dokumentation komplexer Module, damit neue Kolleg:innen sich schnell einarbeiten können.",
    epicor_pd_b3: "Onboarding und Mentoring neuer Entwickler:innen im Team.",
    epicor_pd_b4: "Einsatz KI-gestützter Workflows, um schneller zu liefern, ohne die Review-Qualität zu opfern.",
    hoffmann_b1: "Flashing-Programm für hochpräzise BLE-Industriewerkzeuge über LPUART.",
    hoffmann_b2: "Automatisierte Tests für elektronische Industriewerkzeuge.",
    hoffmann_b3: "End-to-End-Firmware-Tests und reproduzierbare Bug-Reports an das Firmware-Team.",
    epicor_intern_b1: "Front-End-Entwicklung am Flagship-ERP des Unternehmens.",
    proj_e: "Wissen anwenden",
    proj_h: "Projekte",
    proj_lede: "Ein paar Dinge, die ich ausgeliefert habe.",
    proj_bot_t: "Social-Media-Bot + REST-API",
    proj_bot_d: "JavaScript-Bot, gestützt durch NodeJS. Der Bot löst Befehle aus, die sowohl auf System- als auch auf Hardware-Ebene laufen.",
    proj_bank_t: "Datenbankverwaltung",
    proj_bank_d: "MariaDB + Spring Boot — Anwendung modelliert Konten, Überweisungen und allgemeine Informationen einer kleinen Bank.",
    proj_traffic_t: "Mobile App-Entwicklung",
    proj_traffic_d: "Entwicklung einer mobilen App für Unfall- und Verkehrsmeldungen mit dem Ionic-Framework und Google-API-Diensten.",
    proj_flash_t: "Industriewerkzeug-Flasher",
    proj_flash_d: "Firmware-Flashing-Utility für eine Familie von BLE-Präzisionswerkzeugen — LPUART, in Python geschrieben.",
    proj_view: "Details ansehen",
    proj_image_placeholder: "Projektbild",
    voices_e: "Referenzen",
    voices_h: "Stimmen",
    voices_lede: "Auszüge aus Referenzen — vollständige Schreiben auf Anfrage.",
    tm_q1: "[...]Herr Araujo Chavez stets in beeindruckend kurzer Zeit ausgezeichnete Fachkenntnisse und konnte diese immer mit sehr gutem Erfolg in die tägliche Arbeit einbringen und umsetzen.",
    tm_q2: "Er wechselte mühelos zwischen Firmware-Testing und Tooling. Pragmatisch, sorgfältig und angenehm in der Zusammenarbeit.",
    tm_q3: "Ein herausragender Student — neugierig, methodisch und sechs Semester in Folge konstant unter den Besten seines Jahrgangs.",
    tm_r1: "Leiter der Entwicklung für fortschrittliche Steuerungssysteme",
    tm_r2: "Team Lead",
    tm_r3: "Thesis-Betreuer",
    skills_h: "Fähigkeiten",
    skills_langs: "Sprachen",
    skills_frameworks: "Frameworks & Runtimes",
    skills_practice: "Praxis",
    certs_h: "Zertifikate",
    spoken_h: "Gesprochene Sprachen",
    contact_h: "Reden wir",
    contact_lede: "Ich bin offen für Software-Engineering-Rollen — Backend oder Embedded.",
    contact_email: "E-Mail",
    contact_resume: "Lebenslauf (PDF)",
    footer_built: "Eiram Araujo",
    footer_year: "2026",
    tw_theme: "Thema",
    tw_accent: "Akzent",
    tw_motion: "Animation",
    tw_density: "Dichte",
    tw_font: "Schrift",
    lang_label: "Sprache",
    skip_link: "Zum Inhalt springen",
    edu_uanl: "B.Sc. Informatik",
    edu_ovgu: "B.Sc. Informatik — Auslandssemester",
    education_h: "Ausbildung",
    lang_es: "Spanisch",
    lang_en: "Englisch",
    lang_de: "Deutsch",
    lang_jp: "Japanisch",
  },
};

window.RESUME = RESUME;
window.I18N = I18N;
